[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 年度目标
> align=`left`


## 考证

### 1\. 软考中级\(数据库系统工程师\)
- TOPIC
<pre>18CCF86351EA</pre>

### 2\. MySQL OCP认证

### 3\. 专利代理工程师
- TOPIC
<pre>18CCF867B8DA</pre>

## 学习
> topicLinkUID=`18CCF82D84BA`


### 1\. MySQL DBA方向
> topicLinkUID=`18CCF86351EA`


### 2\. 计算机基础

## 搞钱

### 1\. 专利代理
> topicLinkUID=`18CCF867B8DA`


### 2\. 装机
