{
 "title": "wakatime-sync-server",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": "${VAR_APPLICATION}" },
   { "name": "instance", "label": "Instance", "query": "${VAR_INSTANCE}" },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "wakatime-sync-server业务指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "wakatime-sync接口请求次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"wakatime-sync-server\", exception=\"None\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wakatime-sync接口请求耗时(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (uri)(irate(http_server_requests_seconds_sum{application=\"wakatime-sync-server\", exception=\"None\"}[1m]))/sum by (uri)(irate(http_server_requests_seconds_count{application=\"wakatime-sync-server\", exception=\"None\"}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ccm-nt-ip-switch接口请求失败次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (uri) (idelta(http_server_requests_seconds_count{application=\"wakatime-sync-server\", exception!=\"None\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "启动时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"wakatime-sync-server\", instance=\"192.168.1.17:9090\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM堆使用大小/M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by(instance)(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"} / 1024 / 1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pod CPU核心数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"ccm-nat-ip-switch-server.*\", resource=\"cpu\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "JVM堆大小/M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by(instance)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"} / 1024 / 1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM非堆使用大小/M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by(instance)(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"} / 1024 / 1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU核心数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", job=\"kube-state-metrics\", container=\"ccm-nat-ip-switch-server\", pod=~\"ccm-nat-ip-switch-server.*\", resource=\"cpu\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM堆使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum by(instance)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "非堆内存使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum by(instance)(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{instanct}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg(irate (container_cpu_usage_seconds_total{pod=~\"ccm-nat-ip-switch-server.*\", container!=\"promtail-log-sidecar\", namespace=\"$namespace\"}[1m]) * 1000 ) by (pod)\r\n/ avg(container_spec_cpu_quota{pod=~\"ccm-nat-ip-switch-server.*\", container!=\"promtail-log-sidecar\", namespace=\"$namespace\"} / 100)by (pod) * 1000) / 1000",
     "legendFormat": "ccm-nat-ip-switch-server"
    },
    {
     "expr": "(avg(irate (container_cpu_usage_seconds_total{pod=~\"ccm-nat-ip-switch-server.*\", container=\"promtail-log-sidecar\", namespace=\"$namespace\"}[1m]) * 1000 ) by (pod)\r\n/ avg(container_spec_cpu_quota{pod=~\"ccm-nat-ip-switch-server.*\", container=\"promtail-log-sidecar\", namespace=\"$namespace\"} / 100)by (pod) * 1000) / 1000",
     "legendFormat": "promtail-log-sidecar"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "memory_pool_nonheap (non-heap)",
   "type": "graph",
   "description": "堆内存的使用",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Statistisc - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[30s])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Log4j2 Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(log4j2_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}